-- DAP configuration
local dap = require("dap")
local dapui = require("dapui")
local gs = require("gitsigns")
local select = require("nvim-treesitter-textobjects.select")
local move = require("nvim-treesitter-textobjects.move")
local dv = require("diffview.lib")

-- keymaps
vim.g.mapleader = " "
-- neo-tree
vim.keymap.set({ "n", "v" }, "<leader>e", ":Neotree toggle=true <CR>")
-- german keyboard adjustments
vim.keymap.set({ "n", "v", "o" }, "ä", "]", { remap = true, desc = "Alias for ]" })
vim.keymap.set({ "n", "v", "o" }, "ää", "]]", { remap = true, desc = "Alias for ]" })
vim.keymap.set({ "n", "v", "o" }, "ö", "[", { remap = true, desc = "Alias for [" })
vim.keymap.set({ "n", "v", "o" }, "öö", "[[", { remap = true, desc = "Alias for [" })
-- use gt gT and 2gt
-- vim.keymap.set("n", "<leader><tab>ä", "<leader><tab>[", { remap = true, desc = "Previous Tab" })
-- vim.keymap.set("n", "<leader><tab>ö", "<leader><tab>]", { remap = true, desc = "Next Tab" })
vim.keymap.set("n", "<leader><tab><tab>", "<cmd>tabnew<cr>", { desc = "New Tab" })
vim.keymap.set("n", "<leader><tab>c", "<cmd>tabclose<cr>", { desc = "Close Tab" })
-- search
vim.keymap.set("n", "ü", "/", { remap = true, desc = "Search" })
vim.keymap.set("n", "Ü", "?", { remap = true, desc = "Search" })
-- brackets
vim.keymap.set("n", "-", "%", { remap = true, desc = "Percent" })
-- windows
vim.keymap.set("n", "<C-h>", "<C-w>h", { desc = "Move to left window" })
vim.keymap.set("n", "<C-j>", "<C-w>j", { desc = "Move to lower window" })
vim.keymap.set("n", "<C-k>", "<C-w>k", { desc = "Move to upper window" })
vim.keymap.set("n", "<C-l>", "<C-w>l", { desc = "Move to right window" })
-- terminal
vim.keymap.set("n", "<leader>t", function()
	vim.cmd("botright split | terminal")
	vim.cmd("startinsert")
end, { desc = "Open terminal" })
vim.api.nvim_create_autocmd("TermOpen", {
	pattern = "*",
	callback = function()
		vim.keymap.set("t", "<Esc><Esc>", [[<C-\><C-n>]], { buffer = 0 })
	end,
})
-- Picker
vim.keymap.set("n", "<leader><space>", function()
	Snacks.picker.files()
end, { desc = "Find Files" })
vim.keymap.set("n", "<leader>,", function()
	Snacks.picker.buffers()
end, { desc = "Buffers" })
vim.keymap.set("n", "<leader>ü", function()
	Snacks.picker.grep()
end, { desc = "Grep" })
vim.keymap.set("n", "<leader>.", function()
	Snacks.scratch()
end, { desc = "Scratch Buffer" })
-- Notifications
vim.keymap.set("n", "<leader>n", function()
	Snacks.picker.notifications()
end, { desc = "Notification History" })
-- Diagnostics
vim.keymap.set("n", "<leader>d", function()
	Snacks.picker.diagnostics_buffer()
end, { desc = "Buffer Diagnostics" })
vim.keymap.set("n", "<leader>D", function()
	Snacks.picker.diagnostics()
end, { desc = "Diagnostics" })
-- git
vim.keymap.set("n", "<leader>gs", function()
	Snacks.picker.git_status()
end, { desc = "Git Status" })
-- LSP replace default behavior with pickers and preview
vim.keymap.set("n", "gd", function()
	Snacks.picker.lsp_definitions()
end, { desc = "Goto Definition" })
vim.keymap.set("n", "gD", function()
	Snacks.picker.lsp_declarations()
end, { desc = "Goto Declaration" })
vim.keymap.set("n", "gr", function()
	Snacks.picker.lsp_references()
end, { nowait = true, desc = "References" })
vim.keymap.set("n", "gI", function()
	Snacks.picker.lsp_implementations()
end, { desc = "Goto Implementation" })
vim.keymap.set("n", "gy", function()
	Snacks.picker.lsp_type_definitions()
end, { desc = "Goto T[y]pe Definition" })
vim.keymap.set("n", "gai", function()
	Snacks.picker.lsp_incoming_calls()
end, { desc = "C[a]lls Incoming" })
vim.keymap.set("n", "gao", function()
	Snacks.picker.lsp_outgoing_calls()
end, { desc = "C[a]lls Outgoing" })
-- LSP Symbols
vim.keymap.set("n", "<leader>ss", function()
	Snacks.picker.lsp_symbols()
end, { desc = "LSP      Symbols" })
vim.keymap.set("n", "<leader>sS", function()
	Snacks.picker.lsp_workspace_symbols()
end, { desc = "LSP Workspace Symbols" })
-- Git
vim.keymap.set("n", "<leader>gg", function()
	Snacks.lazygit()
end, { desc = "Lazygit" })
-- Registers
vim.keymap.set("n", "<leader>p", function()
	Snacks.picker.registers()
end, { desc = "Registers" })
-- File Explorekr
-- vim.keymap.set("n", "<leader>e", function()
-- 	Snacks.explorer()
-- end, { desc = "File Explorer" })
-- Buffer
vim.keymap.set("n", "<delete>", function()
	Snacks.bufdelete()
end, { desc = "Close Buffer" })
-- flash nvim
vim.keymap.set({ "n", "x", "o" }, "s", function()
	require("flash").jump()
end, { desc = "Flash" })
vim.keymap.set({ "n", "x", "o" }, "S", function()
	require("flash").treesitter()
end, { desc = "Flash Treesitter" })
-- bufferline
vim.keymap.set("n", "L", function()
	vim.cmd("bnext " .. vim.v.count1)
end, { desc = "Next buffer" })
vim.keymap.set("n", "H", function()
	vim.cmd("bprev " .. vim.v.count1)
end, { desc = "Previous buffer" })
vim.keymap.set("n", "<leader>bo", "<cmd>BufferLineCloseOthers<cr>", { desc = "Close other buffers" })
vim.keymap.set("n", "<leader>br", "<cmd>BufferLineCloseRight<cr>", { desc = "Close buffers right" })
vim.keymap.set("n", "<leader>bl", "<cmd>BufferLineCloseLeft<cr>", { desc = "Close buffers left" })
-- window splits
vim.keymap.set("n", "<leader>-", "<cmd>split<cr>", { desc = "Split Horizontal" })
vim.keymap.set("n", "<leader>|", "<cmd>vsplit<cr>", { desc = "Split Vertical" })
-- sessions
vim.keymap.set("n", "<leader>qs", function()
	require("persistence").load()
end)
---- Restore session for current directory
vim.keymap.set("n", "<leader>ql", function()
	require("persistence").load({ last = true })
end)
-- update packages
vim.keymap.set("n", "<leader>uu", ":lua vim.pack.update()<CR>")
-- git hunks
vim.keymap.set("n", "]h", function()
	gs.nav_hunk("next")
end, { desc = "Next Hunk" })
vim.keymap.set("n", "[h", function()
	gs.nav_hunk("prev")
end, { desc = "Prev Hunk" })
-- surround
vim.keymap.set("n", "gsa", "<Plug>(nvim-surround-normal)", { desc = "Add surrounding" })
vim.keymap.set("n", "gsd", "<Plug>(nvim-surround-delete)", { desc = "Delete surrounding" })
vim.keymap.set("n", "gsr", "<Plug>(nvim-surround-change)", { desc = "Replace surrounding" })
-- dial
vim.keymap.set("n", "<C-a>", function()
	require("dial.map").manipulate("increment", "normal")
end, { desc = "Increment" })
vim.keymap.set("n", "<C-x>", function()
	require("dial.map").manipulate("decrement", "normal")
end, { desc = "Decrement" })
vim.keymap.set("x", "<C-a>", function()
	require("dial.map").manipulate("increment", "visual")
end, { desc = "Increment" })
vim.keymap.set("x", "<C-x>", function()
	require("dial.map").manipulate("decrement", "visual")
end, { desc = "Decrement" })
-- functions wrappers
vim.keymap.set("n", "<Esc>", function()
	if vim.v.hlsearch == 1 then
		vim.cmd.nohlsearch()
	end
	return "<Ignore>"
end, { expr = true })
vim.keymap.set("n", "<leader>uw", function()
	vim.wo.wrap = not vim.wo.wrap
end, { desc = "Toggle wrap" })
-- textobjects
vim.keymap.set({ "x", "o" }, "af", function()
	select.select_textobject("@function.outer", "textobjects")
end, { desc = "Select around function" })
vim.keymap.set({ "x", "o" }, "if", function()
	select.select_textobject("@function.inner", "textobjects")
end, { desc = "Select inside function" })
vim.keymap.set({ "x", "o" }, "ac", function()
	select.select_textobject("@class.outer", "textobjects")
end, { desc = "Select around class" })
vim.keymap.set({ "x", "o" }, "ic", function()
	select.select_textobject("@class.inner", "textobjects")
end, { desc = "Select inside class" })
vim.keymap.set({ "x", "o" }, "aa", function()
	select.select_textobject("@parameter.outer", "textobjects")
end, { desc = "Select around parameter" })
vim.keymap.set({ "x", "o" }, "ia", function()
	select.select_textobject("@parameter.inner", "textobjects")
end, { desc = "Select inside parameter" })
vim.keymap.set({ "x", "o" }, "al", function()
	select.select_textobject("@loop.outer", "textobjects")
end, { desc = "Select around loop" })
vim.keymap.set({ "x", "o" }, "il", function()
	select.select_textobject("@loop.inner", "textobjects")
end, { desc = "Select inside loop" })
vim.keymap.set({ "x", "o" }, "aT", function()
	select.select_textobject("@conditional.outer", "textobjects")
end, { desc = "Select around conditional" })
vim.keymap.set({ "x", "o" }, "iT", function()
	select.select_textobject("@conditional.inner", "textobjects")
end, { desc = "Select inside conditional" })
vim.keymap.set({ "x", "o" }, "ab", function()
	select.select_textobject("@block.outer", "textobjects")
end, { desc = "Select around block" })
vim.keymap.set({ "x", "o" }, "ib", function()
	select.select_textobject("@block.inner", "textobjects")
end, { desc = "Select inside block" })
vim.keymap.set({ "x", "o" }, "aC", function()
	select.select_textobject("@comment.outer", "textobjects")
end, { desc = "Select around comment" })
vim.keymap.set({ "x", "o" }, "iC", function()
	select.select_textobject("@comment.inner", "textobjects")
end, { desc = "Select inside comment" })

-- ---- move to next/prev object
vim.keymap.set({ "n", "x", "o" }, "]f", function()
	move.goto_next_start("@function.outer", "textobjects")
end, { desc = "Next function start" })
vim.keymap.set({ "n", "x", "o" }, "]F", function()
	move.goto_next_end("@function.outer", "textobjects")
end, { desc = "Next function end" })
vim.keymap.set({ "n", "x", "o" }, "[f", function()
	move.goto_previous_start("@function.outer", "textobjects")
end, { desc = "Prev function start" })
vim.keymap.set({ "n", "x", "o" }, "[F", function()
	move.goto_previous_end("@function.outer", "textobjects")
end, { desc = "Prev function end" })

vim.keymap.set({ "n", "x", "o" }, "]k", function()
	move.goto_next_start("@class.outer", "textobjects")
end, { desc = "Next class start" })
vim.keymap.set({ "n", "x", "o" }, "]K", function()
	move.goto_next_end("@class.outer", "textobjects")
end, { desc = "Next class end" })
vim.keymap.set({ "n", "x", "o" }, "[k", function()
	move.goto_previous_start("@class.outer", "textobjects")
end, { desc = "Prev class start" })
vim.keymap.set({ "n", "x", "o" }, "[K", function()
	move.goto_previous_end("@class.outer", "textobjects")
end, { desc = "Prev class end" })

vim.keymap.set({ "n", "x", "o" }, "]a", function()
	move.goto_next_start("@parameter.inner", "textobjects")
end, { desc = "Next parameter" })
vim.keymap.set({ "n", "x", "o" }, "]A", function()
	move.goto_next_end("@parameter.inner", "textobjects")
end, { desc = "Next parameter end" })
vim.keymap.set({ "n", "x", "o" }, "[a", function()
	move.goto_previous_start("@parameter.inner", "textobjects")
end, { desc = "Prev parameter" })
vim.keymap.set({ "n", "x", "o" }, "[A", function()
	move.goto_previous_end("@parameter.inner", "textobjects")
end, { desc = "Prev parameter end" })
-- mason
vim.keymap.set("n", "<leader>cm", "<cmd>Mason<CR>", { desc = "Mason UI (LSP tools)" })
-- virtual text
local function virtual_lines_opts()
	return {
		format = function(diagnostic)
			local source = diagnostic.source and (diagnostic.source .. ": ") or ""
			return source .. diagnostic.message
		end,
	}
end

local virtual_lines_on = false
vim.keymap.set("n", "gK", function()
	virtual_lines_on = not virtual_lines_on
	vim.diagnostic.config({
		virtual_lines = virtual_lines_on and virtual_lines_opts() or false,
	})
end, { desc = "Toggle diagnostic virtual_lines" })
-- code actions
vim.keymap.set({ "n", "v" }, "<leader>ca", vim.lsp.buf.code_action, { desc = "Code Actions" })
-- DAP
vim.keymap.set("n", "<F5>", function()
	dap.continue()
end, { desc = "DAP: Continue" })
vim.keymap.set("n", "<F10>", function()
	dap.step_over()
end, { desc = "DAP: Step Over" })
vim.keymap.set("n", "<F11>", function()
	dap.step_into()
end, { desc = "DAP: Step Into" })
vim.keymap.set("n", "<F12>", function()
	dap.step_out()
end, { desc = "DAP: Step Out" })
vim.keymap.set("n", "<leader>db", function()
	dap.toggle_breakpoint()
end, { desc = "DAP: Toggle breakpoint" })
vim.keymap.set("n", "<leader>dB", function()
	dap.set_breakpoint(vim.fn.input("Breakpoint condition: "))
end, { desc = "DAP: Conditional breakpoint" })
vim.keymap.set("n", "<leader>du", function()
	dapui.toggle()
end, { desc = "DAP: Toggle UI" })
vim.keymap.set("n", "<leader>dh", function()
	dapui.eval()
end, { desc = "DAP: Evaluate under cursor" })
vim.keymap.set("n", "<leader>dr", function()
	require("dapui").float_element("repl", { enter = true })
end, { desc = "DAP: Open REPL" })
vim.keymap.set("n", "<leader>bc", function()
	require("dap").clear_breakpoints()
end, { desc = "DAP: Clear all breakpoints" })
-- diff viewA
vim.keymap.set("n", "<leader>gd", function()
	if dv.get_current_view() then
		vim.cmd("DiffviewClose")
	else
		vim.cmd("DiffviewOpen")
	end
end, { desc = "Diffview: toggle working-tree diff" })
vim.keymap.set("n", "<leader>gh", "<cmd>DiffviewFileHistory %<CR>", { desc = "Diffview: file history" })
vim.keymap.set("n", "<leader>gH", "<cmd>DiffviewFileHistory<CR>", { desc = "Diffview: branch history" })
vim.keymap.set("n", "<leader>gm", "<cmd>DiffviewOpen --merge<CR>", { desc = "Diffview: resolve merge conflicts" })
vim.keymap.set("n", "<leader>gR", "<cmd>DiffviewRefresh<CR>", { desc = "Diffview: refresh" })
-- windows
vim.keymap.set("n", "<leader>wc", "<cmd>close<CR>", { desc = "Close window" })
-- test debugging
vim.keymap.set("n", "<leader>tm", function()
	require("dap-python").test_method()
end, { desc = "Debug test method" })
vim.keymap.set("n", "<leader>tc", function()
	require("dap-python").test_class()
end, { desc = "Debug test class" })
